package repo

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

// Channel represents a row in the channels table. Config is exposed as a parsed arbitrary structure.
type Channel struct {
	ID      string `json:"id"`
	Type    string `json:"type"`
	Name    string `json:"name"`
	Config  any    `json:"config,omitempty"`
	AgentID string `json:"agent_id,omitempty"`
	Enabled bool   `json:"enabled"`
}

// ChannelRepo wraps reads/writes for the channels / channel_routes tables.
type ChannelRepo struct {
	db *sql.DB
}

// NewChannelRepo creates a ChannelRepo.
func NewChannelRepo(db *sql.DB) *ChannelRepo { return &ChannelRepo{db: db} }

// List returns all channel instances (with parsed config).
func (r *ChannelRepo) List(ctx context.Context) ([]Channel, error) {
	rows, err := r.db.QueryContext(ctx,
		`SELECT id,type,name,COALESCE(config_json,'{}'),COALESCE(agent_id,''),enabled
		 FROM channels ORDER BY name`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var channels []Channel
	for rows.Next() {
		var c Channel
		var cfgJSON string
		var enabled int
		if err := rows.Scan(&c.ID, &c.Type, &c.Name, &cfgJSON, &c.AgentID, &enabled); err != nil {
			return nil, err
		}
		c.Enabled = enabled == 1
		var cfg any
		_ = json.Unmarshal([]byte(cfgJSON), &cfg)
		c.Config = cfg
		channels = append(channels, c)
	}
	return channels, rows.Err()
}

// ChannelStatus is a lightweight status view without config.
type ChannelStatus struct {
	ID      string `json:"id"`
	Type    string `json:"type"`
	Name    string `json:"name"`
	Enabled bool   `json:"enabled"`
	Running bool   `json:"running"`
}

// Status returns the lightweight status of a single channel.
func (r *ChannelRepo) Status(ctx context.Context, id string) (*ChannelStatus, error) {
	row := r.db.QueryRowContext(ctx,
		`SELECT id,type,name,enabled FROM channels WHERE id=?`, id)
	var s ChannelStatus
	var enabled int
	if err := row.Scan(&s.ID, &s.Type, &s.Name, &enabled); err != nil {
		return nil, err
	}
	s.Enabled = enabled == 1
	return &s, nil
}

// ListStatus returns lightweight status for all channels.
func (r *ChannelRepo) ListStatus(ctx context.Context) ([]ChannelStatus, error) {
	rows, err := r.db.QueryContext(ctx,
		`SELECT id,type,name,enabled FROM channels ORDER BY name`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var list []ChannelStatus
	for rows.Next() {
		var s ChannelStatus
		var enabled int
		if err := rows.Scan(&s.ID, &s.Type, &s.Name, &enabled); err != nil {
			return nil, err
		}
		s.Enabled = enabled == 1
		list = append(list, s)
	}
	return list, rows.Err()
}

// Create inserts a new channel instance (id is generated by SQLite).
func (r *ChannelRepo) Create(ctx context.Context, typ, name string, config any, agentID string) error {
	cfgJSON, _ := json.Marshal(config)
	_, err := r.db.ExecContext(ctx,
		`INSERT INTO channels(id,type,name,config_json,agent_id,enabled,created_at)
		 VALUES(lower(hex(randomblob(16))),?,?,?,?,1,?)`,
		typ, name, string(cfgJSON), nullStr(agentID), time.Now().UnixMilli())
	return err
}

// Update updates a channel; empty name keeps the original, nil enabled leaves the enabled state unchanged.
func (r *ChannelRepo) Update(ctx context.Context, id, name string, config any, agentID string, enabled *bool) error {
	cfgJSON, _ := json.Marshal(config)
	if enabled != nil {
		_, err := r.db.ExecContext(ctx,
			`UPDATE channels SET name=COALESCE(NULLIF(?,''),name),config_json=?,
			  agent_id=NULLIF(?,CAST('' AS TEXT)),enabled=? WHERE id=?`,
			name, string(cfgJSON), agentID, boolInt(*enabled), id)
		return err
	}
	_, err := r.db.ExecContext(ctx,
		`UPDATE channels SET name=COALESCE(NULLIF(?,''),name),config_json=?,
		  agent_id=NULLIF(?,CAST('' AS TEXT)) WHERE id=?`,
		name, string(cfgJSON), agentID, id)
	return err
}

// Delete removes a channel instance and its routes.
func (r *ChannelRepo) Delete(ctx context.Context, id string) error {
	_, _ = r.db.ExecContext(ctx, `DELETE FROM channel_routes WHERE channel_id=?`, id)
	_, err := r.db.ExecContext(ctx, `DELETE FROM channels WHERE id=?`, id)
	return err
}

// DefaultAgent returns the default bound agentID for a channel (empty string if none).
func (r *ChannelRepo) DefaultAgent(ctx context.Context, channelID string) (string, error) {
	var agentID string
	err := r.db.QueryRowContext(ctx,
		`SELECT COALESCE(agent_id,'') FROM channels WHERE id=?`, channelID).Scan(&agentID)
	if err == sql.ErrNoRows {
		return "", nil
	}
	return agentID, err
}

// EnabledRaw holds the raw config of an enabled channel, ready for instantiation.
type EnabledRaw struct {
	ID         string
	Type       string
	ConfigJSON string
}

// ListEnabledRaw reads raw config for all enabled channels, used during startup instantiation.
func (r *ChannelRepo) ListEnabledRaw(ctx context.Context) ([]EnabledRaw, error) {
	rows, err := r.db.QueryContext(ctx,
		`SELECT id,type,COALESCE(config_json,'{}') FROM channels WHERE enabled=1`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var list []EnabledRaw
	for rows.Next() {
		var e EnabledRaw
		if err := rows.Scan(&e.ID, &e.Type, &e.ConfigJSON); err != nil {
			return nil, err
		}
		list = append(list, e)
	}
	return list, rows.Err()
}

// ── channel_routes ───────────────────────────────────────────────────────────

// ResolveRoute looks up the agentID / sessionID mapped by "channel+peer".
// Returns empty strings and found=false when no route matches (caller decides fallback logic).
func (r *ChannelRepo) ResolveRoute(ctx context.Context, channelID, peer string) (agentID, sessionID string, found bool, err error) {
	row := r.db.QueryRowContext(ctx,
		`SELECT COALESCE(agent_id,''),COALESCE(session_id,'')
		 FROM channel_routes WHERE channel_id=? AND peer=?`,
		channelID, peer)
	err = row.Scan(&agentID, &sessionID)
	if err == sql.ErrNoRows {
		return "", "", false, nil
	}
	if err != nil {
		return "", "", false, err
	}
	return agentID, sessionID, true, nil
}

// UpsertRoute creates or updates the "channel+peer → session" route binding.
func (r *ChannelRepo) UpsertRoute(ctx context.Context, id, channelID, peer, agentID, sessionID string) error {
	_, err := r.db.ExecContext(ctx,
		`INSERT INTO channel_routes(id,channel_id,peer,agent_id,session_id)
		 VALUES(?,?,?,?,?)
		 ON CONFLICT(channel_id,peer) DO UPDATE SET session_id=excluded.session_id`,
		id, channelID, peer, agentID, sessionID)
	return err
}
