package repo

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

// ServerConfig represents a row in the mcp_servers table.
type ServerConfig struct {
	ID        string            `json:"id"`
	Name      string            `json:"name"`
	Transport string            `json:"transport"` // stdio | sse | http
	Command   string            `json:"command"`
	Args      []string          `json:"args"`
	URL       string            `json:"url"`
	Env       map[string]string `json:"env"`
	Enabled   bool              `json:"enabled"`
}

// MCPRepo wraps reads/writes for the mcp_servers / mcp_grants tables.
type MCPRepo struct {
	db *sql.DB
}

// NewMCPRepo creates an MCPRepo.
func NewMCPRepo(db *sql.DB) *MCPRepo { return &MCPRepo{db: db} }

// List reads all MCP server configurations.
func (r *MCPRepo) List(ctx context.Context) ([]ServerConfig, error) {
	rows, err := r.db.QueryContext(ctx,
		`SELECT id,name,transport,COALESCE(command,''),COALESCE(args_json,'[]'),
		  COALESCE(url,''),COALESCE(env_json,'{}'),enabled
		 FROM mcp_servers ORDER BY name`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var servers []ServerConfig
	for rows.Next() {
		var s ServerConfig
		var argsJSON, envJSON string
		var enabled int
		if err := rows.Scan(&s.ID, &s.Name, &s.Transport, &s.Command,
			&argsJSON, &s.URL, &envJSON, &enabled); err != nil {
			return nil, err
		}
		s.Enabled = enabled == 1
		_ = json.Unmarshal([]byte(argsJSON), &s.Args)
		_ = json.Unmarshal([]byte(envJSON), &s.Env)
		servers = append(servers, s)
	}
	return servers, rows.Err()
}

// Add inserts a new MCP server configuration (id is generated by SQLite).
func (r *MCPRepo) Add(ctx context.Context, cfg ServerConfig) error {
	argsJSON, _ := json.Marshal(cfg.Args)
	envJSON, _ := json.Marshal(cfg.Env)
	_, err := r.db.ExecContext(ctx,
		`INSERT INTO mcp_servers(id,name,transport,command,args_json,url,env_json,enabled,created_at)
		 VALUES(lower(hex(randomblob(16))),?,?,?,?,?,?,1,?)`,
		cfg.Name, cfg.Transport, cfg.Command, string(argsJSON),
		cfg.URL, string(envJSON), time.Now().UnixMilli())
	return err
}

// Update updates an MCP server configuration.
func (r *MCPRepo) Update(ctx context.Context, cfg ServerConfig) error {
	argsJSON, _ := json.Marshal(cfg.Args)
	envJSON, _ := json.Marshal(cfg.Env)
	_, err := r.db.ExecContext(ctx,
		`UPDATE mcp_servers SET name=?,transport=?,command=?,args_json=?,url=?,env_json=?
		 WHERE id=?`,
		cfg.Name, cfg.Transport, cfg.Command, string(argsJSON),
		cfg.URL, string(envJSON), cfg.ID)
	return err
}

// Delete removes an MCP server configuration and its grant relationships.
func (r *MCPRepo) Delete(ctx context.Context, id string) error {
	_, _ = r.db.ExecContext(ctx, `DELETE FROM mcp_grants WHERE server_id=?`, id)
	_, err := r.db.ExecContext(ctx, `DELETE FROM mcp_servers WHERE id=?`, id)
	return err
}

// Grant authorizes an agent to use an MCP server.
func (r *MCPRepo) Grant(ctx context.Context, serverID, agentID string) error {
	_, err := r.db.ExecContext(ctx,
		`INSERT OR IGNORE INTO mcp_grants(server_id,agent_id) VALUES(?,?)`,
		serverID, agentID)
	return err
}

// Revoke removes an agent's authorization for an MCP server.
func (r *MCPRepo) Revoke(ctx context.Context, serverID, agentID string) error {
	_, err := r.db.ExecContext(ctx,
		`DELETE FROM mcp_grants WHERE server_id=? AND agent_id=?`, serverID, agentID)
	return err
}
