-- 0005_agent_chat_model.up.sql
-- Add a `chat_model` column to the agents table.
--
-- For to-image / to-video agents, the value in `model` points at the diffusion
-- weights (delegated to sd-server) and is NOT a chat-capable LLM. To still
-- have the agent be able to converse with the user — for example to refine the
-- generation prompt or to summarise the produced media — we need a separate
-- chat-capable model.
--
-- For to-text agents this column is unused (NULL); the standard llama loop
-- continues to use `model` directly.
ALTER TABLE agents ADD COLUMN chat_model TEXT;
